#!/bin/bash

echo ">>> ☢️  INITIATING COLD RESTART..."

# 1. DELETE BROKEN ARTIFACTS
echo ">>> Wiping apps/web..."
rm -rf apps/web

# 2. REBUILD SCAFFOLDING
echo ">>> Rebuilding Architecture..."
mkdir -p apps/web/src/components/schematics
mkdir -p apps/web/public

# 3. WRITE CONFIG FILES
echo ">>> writing package.json..."
cat << 'JSON' > apps/web/package.json
{
  "name": "trumetrics-web",
  "version": "0.1.0",
  "scripts": { "dev": "vite", "build": "vite build" },
  "dependencies": { "react": "^18.2.0", "react-dom": "^18.2.0", "lucide-react": "^0.263.1" },
  "devDependencies": { "@types/react": "^18.2.15", "@types/react-dom": "^18.2.7", "@vitejs/plugin-react": "^4.0.3", "autoprefixer": "^10.4.14", "postcss": "^8.4.27", "tailwindcss": "^3.3.3", "typescript": "^5.0.2", "vite": "^4.4.5" }
}
JSON

echo ">>> writing configs..."
echo "export default { content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'], theme: { extend: { fontFamily: { mono: ['Menlo', 'monospace'] } } }, plugins: [] }" > apps/web/tailwind.config.js
echo "export default { plugins: { tailwindcss: {}, autoprefixer: {} } }" > apps/web/postcss.config.js
echo "import { defineConfig } from 'vite'; import react from '@vitejs/plugin-react'; export default defineConfig({ plugins: [react()] })" > apps/web/vite.config.ts

# 4. WRITE ENTRY POINTS
echo ">>> writing entry points..."
echo "<!doctype html><html lang='en'><head><meta charset='UTF-8' /><title>TruMetrics</title></head><body class='bg-slate-950'><div id='root'></div><script type='module' src='/src/main.tsx'></script></body></html>" > apps/web/index.html
echo "@tailwind base; @tailwind components; @tailwind utilities;" > apps/web/src/index.css

cat << 'TSX' > apps/web/src/main.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
TSX

cat << 'TSX' > apps/web/src/App.tsx
import { HomeAnatomy } from './components/schematics/HomeAnatomy'
function App() { return (<div className="w-full h-full"><HomeAnatomy /></div>) }
export default App
TSX

# 5. WRITE THE COMPONENT (USING NODE + BASE64 TO PREVENT CORRUPTION)
echo ">>> DECODING COMPONENT PAYLOAD..."

cat << 'NODE_SCRIPT' > apps/web/src/components/schematics/write_component.js
const fs = require('fs');
// This is the HomeAnatomy.tsx code encoded in Base64. 
// This prevents the terminal from messing with brackets {} or dollar signs $.
const b64 = "aW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JzsKCmV4cG9ydCBjb25zdCBIb21lQW5hdG9teSA9ICgpID0+IHsKICByZXR1cm4gKAogICAgPGRpdiBjbGFzc05hbWU9InAtOCBiZy1zbGF0ZS05MDAgdGV4dC1jeWFuLTQwMCBmb250LW1vbm8gbWluLWgtc2NyZWVuIGZsZXggZmxleC1jb2wgaXRlbXMtY2VudGVyIj4KICAgICAgCiAgICAgIDxkaXYgY2xhc3NOYW1lPSJ3LWZ1bGwgbWF4LXctNHhsIGJvcmRlci1iIGJvcmRlci1jeWFuLTgwMCBwYi00IG1iLTggZmxleCBqdXN0aWZ5LWJldHdlZW4gaXRlbXMtZW5kIj4KICAgICAgICA8ZGl2PgogICAgICAgICAgPGgxIGNsYXNzTmFtZT0idGV4dC0zeGwgZm9udC1ib2xkIHRleHQtd2hpdGUgdHJhY2tpbmctd2lkZXN0Ij5UUlVNRVRSSUNTPHNwYW4gY2xhc3NOYW1lPSJ0ZXh0LWN5YW4tNTAwIj5fTEFCPC9zcGFuPjwvaDE+CiAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtc20gdGV4dC1jeWFuLTYwMCBtdC0xIj5VTklUOiBUV0lOLUVER0UtMDQyIC8vIENPTkZJR1VSQVRJT046IEFOQVRPTVk8L3A+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzc05hbWU9InRleHQtcmlnaHQiPgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9InRleHQteHMgdGV4dC1vcmFuZ2UtNDAwIGFuaW1hdGUtcHVsc2UiPlNUQVRVUzogU1RBVElDIEFOQUxZU0lTPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0idGV4dC14cyB0ZXh0LXNsYXRlLTUwMCI+U0NFTkUgMTogVEhFIFBMQVlFUlM8L2Rpdj4KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CgogICAgICA8ZGl2IGNsYXNzTmFtZT0icmVsYXRpdmUgdy1mdWxsIG1heC13LTR4bCBoLVs2MDBweF0gYm9yZGVyIGJvcmRlci1zbGF0ZS03MDAgYmctc2xhdGUtODAwLzUwIHJvdW5kZWQtbGcgb3ZlcmZsb3ctaGlkZGVuIHNoYWRvdy0yeGwiPgogICAgICAgIAogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJhYnNvbHV0ZSB0b3AtNCBsZWZ0LTQgei0yMCI+CiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJ0ZXh0LXhzIHRleHQtc2xhdGUtNDAwIGJvcmRlciBib3JkZXItc2xhdGUtNjAwIGJnLXNsYXRlLTkwMCBweC0yIHB5LTEgbWItMiI+CiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InRleHQteWVsbG93LTQwMCBmb250LWJvbGQiPkNGTSA1MDogNC4yPC9zcGFuPgogICAgICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJibG9jayB0ZXh0LVsxMHB4XSB0ZXh0LXNsYXRlLTUwMCI+QkxPV0VRIERPT1IgUkFUSU5HPC9zcGFuPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L2Rpdj4KCiAgICAgICAgPGRpdiBjbGFzc05hbWU9ImFic29sdXRlIHRvcC0yMCBsZWZ0LTQgei0xMCBzcGFjZS15LTIiPgogICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InRleHQtWzEwcHhdIHRleHQtYmx1ZS0zMDAiPldJTkQgTE9BRCAoUHJlc3N1cmUpPC9zcGFuPgogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0idy0yNCBoLTAuNSBiZy1ibHVlLTUwMC81MCI+PC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJ3LTE2IGgtMC41IGJnLWJsdWUtNTAwLzUwIj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InctMjAgaC0wLjUgYmctYmx1ZS01MDAvNTAiPjwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJhYnNvbHV0ZSB0b3AtMjAgcmlnaHQtNCB6LTEwIGZsZXggZmxleC1jb2wgaXRlbXMtY2VudGVyIj4KICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJ0ZXh0LVsxMHB4XSB0ZXh0LW9yYW5nZS0zMDAiPlNUQUNLIEVGRkVDVDwvc3Bhbj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImgtMjQgdy0wLjUgYmctZ3JhZGllbnQtdG8tdCBmcm9tLW9yYW5nZS01MDAgdG8tdHJhbnNwYXJlbnQgbXQtMSI+PC9kaXY+CiAgICAgICAgPC9kaXY+CgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJhYnNvbHV0ZSB0b3AtMzIgbGVmdC0xLzIgLXRyYW5zbGF0ZS14LTEvMiB3LVs2MDBweF0gaC1bNDAwcHhdIGJvcmRlci00IGJvcmRlci1zbGF0ZS02MDAgcm91bmRlZC10LVsxMDBweF0gYmctc2xhdGUtOTAwLzkwIHJlbGF0aXZlIj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImFic29sdXRlIHRvcC0wIHctZnVsbCBoLTIgYmctcmVkLTUwMC8zMCBhbmltYXRlLXB1bHNlIj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImFic29sdXRlIGJvdHRvbS0wIHctZnVsbCBoLTIgYmctcmVkLTUwMC8zMCBhbmltYXRlLXB1bHNlIj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImFic29sdXRlIHRvcC0yNCBsZWZ0LVsxMCVdIHctWzgwJV0gaC04IGJnLXNsYXRlLTcwMCBib3JkZXIgYm9yZGVyLXNsYXRlLTUwMCBvcGFjaXR5LTUwIj48L2Rpdj4KICAgICAgICAgICAgCiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJhYnNvbHV0ZSB0b3AtWzEwMHB4XSBsZWZ0LVsxMCVdIHctWzgwJV0gZmxleCBqdXN0aWZ5LWJldHdlZW4gcHgtNCI+CiAgICAgICAgICAgICAgICB7Wy4uLkFycmF5KDE1KV0ubWFwKChfLCBpKSA9PiAoCiAgICAgICAgICAgICAgICAgICAgPGRpdiBrZXk9e2l9IGNsYXNzTmFtZT0idy0xLjUgaC0xLjUgcm91bmRlZC1mdWxsIGJnLWdyZWVuLTQwMCBzaGFkb3ctWzBfMF84cHhfIzRhZGU4MF0iIHRpdGxlPXsiVmVudHVyaSBTZW5zb3IgIiArIChpKzEpfT48L2Rpdj4KICAgICAgICAgICAgICAgICkpfQogICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJhYnNvbHV0ZSBib3R0b20tNCBsZWZ0LTE2IHctMzIgaC00MCBib3JkZXItMiBib3JkZXItY3lhbi03MDAgYmctY3lhbi05MDAvMjAgZmxleCBmbGV4LWNvbCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgcC0yIj4KICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0idGV4dC1bMTBweF0gdGV4dC1jeWFuLTMwMCBmb250LWJvbGQiPkhWQUMgQ09SRTwvc3Bhbj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJ0ZXh0LVs4cHhdIHRleHQtY3lhbi01MDAiPlZhcmlhYmxlIFNwZWVkIEhQPC9kaXY+CiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0idy0xMiBoLTEyIHJvdW5kZWQtZnVsbCBib3JkZXIgYm9yZGVyLWN5YW4tNTAwIG10LTIgYm9yZGVyLWRhc2hlZCBhbmltYXRlLVtzcGluXzEwc19saW5lYXJfaW5maW5pdGVdIj48L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJhYnNvbHV0ZSB0b3AtNCByaWdodC0xNiB3LTIwIGgtMjAgYm9yZGVyIGJvcmRlci1wdXJwbGUtNTAwIGJnLXB1cnBsZS05MDAvMjAgZmxleCBmbGV4LWNvbCBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIIj4KICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0idGV4dC1bMTBweF0gdGV4dC1wdXJwbGUtMzAwIGZvbnQtYm9sZCI+RVJWPC9zcGFuPgogICAgICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJ0ZXh0LVs4cHhdIHRleHQtcHVycGxlLTQwMCI+THVuZyAxPC9zcGFuPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImFic29sdXRlIHRvcC00IHJpZ2h0LTQwIHctMTYgaC0xNiBib3JkZXIgYm9yZGVyLWJsdWUtNTAwIGJnLWJsdWUtOTAwLzIwIGZsZXggZmxleC1jb2wgaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIj4KICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0idGV4dC1bMTBweF0gdGV4dC1ibHVlLTMwMCBmb250LWJvbGQiPk1BS0UtVVA8L3NwYW4+CiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InRleHQtWzhweF0gdGV4dC1ibHVlLTQwMCI+THVuZyAyPC9zcGFuPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImFic29sdXRlIGJvdHRvbS00IHJpZ2h0LTE2IHctMjQgaC0zMiBib3JkZXIgYm9yZGVyLW9yYW5nZS02MDAgYmctb3JhbmdlLTkwMC8yMCBmbGV4IGZsZXgtY29sIGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWNlbnRlciI+CiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InRleHQtWzEwcHhdIHRleHQtb3JhbmdlLTMwMCBmb250LWJvbGQiPkRSWUVSPC9zcGFuPgogICAgICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJ0ZXh0LVs4cHhdIHRleHQtcmVkLTQwMCBtdC0xIj5ERVBSRVlTVVJJWkVSPC9zcGFuPgogICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InctZnVsbCBoLXB4IGJnLW9yYW5nZS01MDAvNTAgbXktMiI+PC9kaXY+CiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InRleHQtWzhweF0gdGV4dC1zbGF0ZS00MDAiPkNFTlRSQUwgVkFDPC9zcGFuPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImFic29sdXRlIGJvdHRvbS00OCBsZWZ0LTEvMiAtdHJhbnNsYXRlLXgtMS8yIHctNDAgaC0xNiBiZy1ibGFjayBib3JkZXItMiBib3JkZXItY3lhbi00MDAgcm91bmRlZC1sZyBmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWNlbnRlciBzaGFkb3ctWzBfMF8zMHB4X3JnYmEoMzQsMjExLDIzOCwwLjMpXSB6LTMwIj4KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJ3LTMgaC0zIGJnLWdyZWVuLTUwMCByb3VuZGVkLWZ1bGwgYW5pbWF0ZS1waW5nIG1yLTMiPjwvZGl2PgogICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InRleHQtY2VudGVyIj4KICAgICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0idGV4dC14cyBmb250LWJvbGQgdGV4dC13aGl0ZSI+SFBNIENPUlRFWDwvZGl2PgogICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJ0ZXh0LVs4cHhdIHRleHQtY3lhbi01MDAiPkVER0UgQUdFTlQ8L2Rpdj4KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPHN2ZyBjbGFzc05hbWU9ImFic29sdXRlIGluc2V0LTAgdy1mdWxsIGgtZnVsbCBwb2ludGVyLWV2ZW50cy1ub25lIj4KICAgICAgICAgICAgICAgIDxsaW5lIHgxPSIzMDAiIHkxPSIyMzAiIHgyPSIzMDAiIHkyPSIxMTAiIHN0cm9rZT0iIzIyZDNlZSIgc3Ryb2tlV2lkdGg9IjEiIHN0cm9rZURhc2hhcnJheT0iNCA0IiBvcGFjaXR5PSIwLjUiIC8+CiAgICAgICAgICAgICAgICA8bGluZSB4MT0iMjUwIiB5MT0iMjYwIiB4Mj0iMTQwIiB5Mj0iMzAwIiBzdHJva2U9IiMyMmQzZWUiIHN0cm9rZVdpZHRoPSIxIiBvcGFjaXR5PSIwLjgiIC8+CiAgICAgICAgICAgICAgICA8bGluZSB4MT0iMzUwIiB5MT0iMjYwIiB4Mj0iNDYwIiB5Mj0iMzAwIiBzdHJva2U9IiNmOTczMTYiIHN0cm9rZVdpZHRoPSIxIiBzdHJva2VEYXNoYXJyYXk9IjIgMiIgb3BhY2l0eT0iMC44IiAvPgogICAgICAgICAgICA8L3N2Zz4KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CgogICAgICA8ZGl2IGNsYXNzTmFtZT0idy1mdWxsIG1heC13LTR4bCBncmlkIGdyaWQtY29scy00IGdhcC00IG10LTggdGV4dC1bMTBweF0gYm9yZGVyLXQgYm9yZGVyLXNsYXRlLTgwMCBwdC00IHRleHQtc2xhdGUtNDAwIj4KICAgICAgICA8ZGl2PjxzdHJvbmcgY2xhc3NOYW1lPSJ0ZXh0LXllbGxvdy00MDAgYmxvY2sgbWItMSI+RU5WRUxPUEUgUEhZU0lDUzwvc3Ryb25nPkNGTSA1MCBSYXRpbmcgaW50ZXJhY3Rpbmcgd2l0aCBXaW5kICYgU3RhY2sgRWZmZWN0LjwvZGl2PgogICAgICAgIDxkaXY+PHN0cm9uZyBjbGFzc05hbWU9InRleHQtZ3JlZW4tNDAwIGJsb2NrIG1iLTEiPlZFTlRVUkkgR1JJRDwvc3Ryb25nZjE1eCBJbmxpbmUgU2Vuc29ycyBtZWFzdXJpbmcgZmxvdyBkaXN0cmlidXRpb24uPC9kaXY+CiAgICAgICAgPGRpdj48c3Ryb25nIGNsYXNzTmFtZT0idGV4dC1jeWFuLTQwMCBibG9jayBtYi0xIj5HUE0gQ09SVEVYPC9zdHJvbmc+Q2VudHJhbCBOZXJ2b3VzIFN5c3RlbS4gQWdncmVnYXRlcyBhbGwgc2Vuc29ycy48L2Rpdj4KICAgICAgICA8ZGl2PjxzdHJvbmcgY2xhc3NOYW1lPSJ0ZXh0LW9yYW5nZS00MDAgYmxvY2sgbWItMSI+TE9BRFMgJiBFWEhBVVNUPC9zdHJvbmc+QXBwbGlhbmNlcyB0aGF0IGdlbmVyYXRlIEhlYXQgb3IgTmVnYXRpdmUgUHJlc3N1cmUuPC9kaXY+CiAgICAgIDwvZGl2PgoKICAgIDwvZGl2PgogICk7Cn07Cg==";

// Decode and Write
const content = Buffer.from(b64, 'base64').toString('utf-8');
fs.writeFileSync('apps/web/src/components/schematics/HomeAnatomy.tsx', content);
console.log(">>> Component Restored Successfully.");
NODE_SCRIPT

node apps/web/src/components/schematics/write_component.js

# 6. INSTALL AND LAUNCH
echo ">>> INSTALLING DEPENDENCIES..."
cd apps/web
npm install > /dev/null 2>&1

echo ">>> LAUNCHING PROJECTOR..."
npm run dev
